### ISSUE TITLE
Keep generating words N times until edit distance is non-zero

### ISSUE THREAD

**Issue by Sasafrass** [Sasafrass/straattaal#34]
Keep generating a new word N times until the edit distance to all items in dataset is non-zero. This increases the probability that we generate a word that is not identical to something in the dataset.

**Comment by annaproxy** [comment]
Should we check the word against all possible training set files? (I just removed needing to load the dataset when generating a word, but now I will have to load it anyway :) )

**Comment by annaproxy** [comment]
#41
