### ISSUE TITLE
Remove rnn_generator.ipynb and generate.ipynb if no longer needed.

### ISSUE THREAD

**Issue by Sasafrass** [Sasafrass/straattaal#42]
If these two notebooks are no longer needed for research / future reference purposes why might as well dispose of them. Nit: they kind of make the repository look like a jupyter notebook repo.

**Comment by annaproxy** [comment]
How do you feel about a "notebooks" directory for this purpose?

**Comment by Sasafrass** [comment]
Yeah that works for me. It's always a little sad though that they influence the language makeup of the repo

**Comment by annaproxy** [comment]
#49
